"""CLAUDE.md generator for project onboarding.

Generates a CLAUDE.md section with technology stack, API contract,
type definitions, API clients, project conventions, and FE development rules.
"""

from __future__ import annotations

from pathlib import Path

from helios.indexing.api_extractor import ApiSurface
from helios.indexing.stack_analyzer import StackAnalysis

HELIOS_START = "<!-- HELIOS:START -->"
HELIOS_END = "<!-- HELIOS:END -->"


def generate_claude_md(
    project_name: str,
    project_path: str,
    api_surface: ApiSurface,
    ecosystems: list[str],
    file_count: int,
    dep_count: int,
    stack: StackAnalysis | None = None,
) -> str:
    """Generate the Helios section content for a CLAUDE.md file."""
    lines: list[str] = [
        HELIOS_START,
        f"# {project_name} — Development Rules (Helios)",
        "",
        "> Auto-generated by Helios context intelligence engine.",
        "> Re-run `helios_onboard` to refresh after structural changes.",
        "",
        "## Project Overview",
        "",
        f"- **Path**: `{project_path}`",
    ]

    if api_surface.frameworks:
        lines.append(f"- **Frameworks detected**: {', '.join(api_surface.frameworks)}")
    if ecosystems:
        lines.append(f"- **Ecosystems**: {', '.join(ecosystems)}")
    lines.append(f"- **Files indexed**: {file_count}")
    if dep_count:
        lines.append(f"- **Dependencies indexed**: {dep_count}")

    # --- Technology Stack ---
    if stack and stack.libraries:
        lines.extend(["", "## Technology Stack", ""])
        lines.append(
            "**Use ONLY the libraries listed below.** Do not install or import "
            "alternatives unless explicitly asked by the user."
        )
        lines.append("")

        # Group by category
        by_category: dict[str, list[str]] = {}
        for lib in stack.libraries:
            cat = lib.category.replace("_", " ").title()
            entry = f"`{lib.name}`" + (f" ({lib.version})" if lib.version else "")
            by_category.setdefault(cat, []).append(entry)

        for cat, libs in by_category.items():
            lines.append(f"- **{cat}**: {', '.join(libs)}")

    # --- API Clients ---
    if stack and stack.api_clients:
        lines.extend(["", "## Existing API Clients", ""])
        lines.append(
            "**Use these existing clients for API calls.** Do not create new "
            "fetch/axios wrappers — use what already exists."
        )
        lines.append("")
        for client in stack.api_clients:
            lines.append(f"- **`{client.file_path}`** ({client.kind}): {client.description}")

    # --- API Contract ---
    lines.extend(["", "## API Contract", ""])

    if api_surface.endpoints:
        lines.append(
            "The backend exposes the following endpoints. **Do not create frontend "
            "API calls to endpoints not listed here.** If you need a new endpoint, "
            "implement the backend first."
        )
        lines.append("")
        lines.append("| Method | Path | Handler | File | Request | Response | Framework |")
        lines.append("|--------|------|---------|------|---------|----------|-----------|")

        for ep in sorted(api_surface.endpoints, key=lambda e: (e.path, e.method)):
            req = ep.request_type or "-"
            res = ep.response_type or "-"
            lines.append(
                f"| {ep.method} | `{ep.path}` | {ep.handler} "
                f"| {ep.file_path} | {req} | {res} | {ep.framework} |"
            )
    else:
        lines.append(
            "No API endpoints were automatically detected. Use `helios_search` "
            "to find backend code manually, or check that the backend uses a "
            "supported framework (Next.js App Router, FastAPI, NestJS, Express)."
        )

    # --- Types and Schemas ---
    if stack and stack.type_defs:
        lines.extend(["", "## Types and Schemas", ""])
        lines.append(
            "These type definitions exist in the codebase. **Use them as-is** — "
            "do not redefine or create duplicates."
        )
        lines.append("")

        # Show API-related types in detail, others as a list
        api_types = [t for t in stack.type_defs if _is_api_type(t.name)]
        other_types = [t for t in stack.type_defs if not _is_api_type(t.name)]

        if api_types:
            lines.append("### API Types (use for request/response typing)")
            lines.append("")
            for td in api_types[:30]:  # cap at 30
                lines.append(f"- **`{td.name}`** ({td.kind}) — `{td.file_path}:{td.line_number + 1}`")
            if len(api_types) > 30:
                lines.append(f"- ... and {len(api_types) - 30} more (use `helios_search` to find them)")
            lines.append("")

        if other_types:
            lines.append(f"### Other Types ({len(other_types)} found)")
            lines.append("")
            # Show first 20 as a compact list
            for td in other_types[:20]:
                lines.append(f"- `{td.name}` ({td.kind}) — `{td.file_path}`")
            if len(other_types) > 20:
                lines.append(f"- ... and {len(other_types) - 20} more")
            lines.append("")

    # --- Project Conventions ---
    if stack and stack.patterns:
        p = stack.patterns
        lines.extend(["", "## Project Conventions", ""])
        lines.append("**Follow these patterns consistently.** Match the existing codebase style.")
        lines.append("")

        if p.naming_convention != "not detected":
            lines.append(f"- **File naming**: {p.naming_convention}")
        if p.component_style != "not detected":
            lines.append(f"- **Component style**: {p.component_style}")

        if p.folder_structure:
            lines.append("")
            lines.append("### Project Structure")
            lines.append("")
            for folder, purpose in p.folder_structure.items():
                lines.append(f"- `{folder}/` — {purpose}")

    # --- FE Development Rules ---
    lines.extend([
        "",
        "## Frontend Development Rules",
        "",
        "1. **API calls must match the contract above.** Before creating any "
        "API call, verify the endpoint exists in the API Contract table. "
        "If it does not exist, stop and inform the user.",
        "",
        "2. **Do not invent endpoints.** Never assume an API endpoint exists. "
        "If the feature requires a backend change, flag it explicitly.",
        "",
        "3. **Use the correct HTTP method.** Match the Method column exactly.",
        "",
        "4. **Respect request/response types.** When a Request type is specified, "
        "the payload must conform to that shape. When a Response type is specified, "
        "type the frontend response accordingly.",
        "",
    ])

    if stack and stack.libraries:
        lines.extend([
            "5. **Use only installed libraries.** Do not install new packages "
            "or import libraries not listed in the Technology Stack section. "
            "If a feature needs a new library, ask the user first.",
            "",
        ])
        rule_num = 6
    else:
        rule_num = 5

    if stack and stack.api_clients:
        lines.extend([
            f"{rule_num}. **Use existing API clients.** Do not create new fetch "
            "wrappers or axios instances. Use the clients listed in the "
            "Existing API Clients section.",
            "",
        ])
        rule_num += 1

    if stack and stack.type_defs:
        lines.extend([
            f"{rule_num}. **Reuse existing types.** Before creating a new TypeScript "
            "interface or type, check the Types and Schemas section. Import "
            "existing types rather than redefining them.",
            "",
        ])
        rule_num += 1

    lines.extend([
        f"{rule_num}. **New endpoints require backend-first development.** If a UI "
        "feature needs an endpoint not in the contract, implement the backend "
        "route first, re-run `helios_onboard` to update, then build the frontend.",
        "",
        f"{rule_num + 1}. **Check Helios before guessing.** Use `helios_search` to find "
        "relevant code before making assumptions about API behavior or data shapes.",
        "",
        "## Helios Commands",
        "",
        "- `helios_search \"query\"` — find relevant backend/frontend code",
        "- `helios_context \"task description\"` — get multi-source context for a task",
        "- `helios_api` — list all known API endpoints",
        "- `helios_explore \"source_name\"` — browse project file structure",
        "",
        HELIOS_END,
    ])

    return "\n".join(lines)


def _is_api_type(name: str) -> bool:
    """Check if a type name looks API-related."""
    api_hints = ("Request", "Response", "Dto", "Schema", "Payload", "Input", "Output", "Params", "Body")
    return any(hint in name for hint in api_hints)


def write_claude_md(project_path: str, helios_section: str) -> str:
    """Write or update the Helios section in a project's CLAUDE.md.

    - If no CLAUDE.md exists, creates one with just the Helios section.
    - If CLAUDE.md exists without markers, appends the section.
    - If CLAUDE.md exists with markers, replaces only the Helios section.

    Returns the path to the written file.
    """
    claude_md = Path(project_path) / "CLAUDE.md"
    output_path = str(claude_md)

    if claude_md.exists():
        existing = claude_md.read_text()

        if HELIOS_START in existing and HELIOS_END in existing:
            # Replace existing Helios section
            start = existing.index(HELIOS_START)
            end = existing.index(HELIOS_END) + len(HELIOS_END)
            updated = existing[:start] + helios_section + existing[end:]
            claude_md.write_text(updated)
        else:
            # Append Helios section
            separator = "\n\n" if existing.strip() else ""
            claude_md.write_text(existing.rstrip() + separator + helios_section + "\n")
    else:
        claude_md.write_text(helios_section + "\n")

    return output_path
